### ISSUE TITLE
dbcompiler Broken on non-internet enabled servers

### ISSUE THREAD

**Issue by jdwhited** [puppetlabs/puppet_metrics_dashboard#127]
## Use Case
manifests/profile/dbcompiler/install.pp requires internet access to use.  

## Describe the Solution You Would Like
Please expose telegraf::manage_repo as an optional parameter in this profile (dbcompiler::install) to enable use on non-internet connected servers.

## Describe Alternatives You've Considered
I attempted workarounds involving yum, but the enforcement of the repo is pretty strong and those attempts did not work.

**Comment by suckatrash** [comment]
This should be addressed by #129
