### ISSUE TITLE
Collect System Metrics in Telegraf

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppet_metrics_dashboard#134]
## Use Case
Provide a dashboard for the system metrics for the servers running Puppet services. This should include

* Disk space
* Memory consumption
* CPU Usage
* Swap usage

**Comment by genebean** [comment]
If someone implements collection of these metrics, please do so in an opt-in way as many of us already collect said metrics across all hosts via other profiles.

**Comment by jarretlavallee** [comment]
This seems like something that should not be in this module. Closing as it is not needed.
