### ISSUE TITLE
setting grafana_password doesn't actually do anything

### ISSUE THREAD

**Issue by suckatrash** [puppetlabs/puppet_metrics_dashboard#24]
Not sure how I overlooked this, but the admin user needs to be managed as a resource so that the admin password can be set.

https://forge.puppet.com/puppet/grafana#grafanauser

**Comment by genebean** [comment]
Found how to do it...

```
curl -X PUT -H "Content-Type: application/json" -d '{
  "oldPassword": "admin",
  "newPassword": "newpass",
  "confirmNew": "newpass"
}' http://admin:admin@<your_grafana_host>:3000/api/user/password
```

**Comment by genebean** [comment]
or `grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" newpass`
