### ISSUE TITLE
Populate host params from PuppetDB

### ISSUE THREAD

**Issue by suckatrash** [puppetlabs/puppet_metrics_dashboard#46]

**Comment by suckatrash** [comment]
* `master_list`
* `puppetdb_list`
* `postgres_host_list`

**Comment by suckatrash** [comment]
Discussed this recently and there isn't really a way to do this that would cover both PE and open source implementations.  Closing as won't do.

**Comment by genebean** [comment]
I disagree @suckatrash ... you can check for it being PE and, if so, populate them. There are other things in here that assume PE already so I don't think that is an anti-pattern.

**Comment by suckatrash** [comment]
@genebean I'll reopen if you think it's work looking at some more.  My question is how do we populate hosts when the installation is not PE?  ... I guess we just default to the current behavior where the user must pass in a list of hosts in that case?

**Comment by npwalker** [comment]
It would probably make sense to consider this module a companion to the metrics collector and just use the same things it does.  

Tom added a function for auto-populating those parameters to the metrics collector already which could be used directly if it was a dependency here.  Similarly the puppetdb_metrics function could have been made in the collector and then used both places.

**Comment by tkishel** [comment]
This module already queries PuppetDB in the `postgres_access` class.
Not ready to establish a dependency, so I'll submit a PR ...

**Comment by suckatrash** [comment]
This was implemented with PR #81
