### ISSUE TITLE
Consider dropping pe- prefix from example dashboards

### ISSUE THREAD

**Issue by Sharpie** [puppetlabs/puppet_metrics_dashboard#47]
In Puppet Server 5 the metrics, which had previously been a PE only feature, were moved to the open source build. This means that items like `pe-jruby-metrics` and `pe-puppet-profiler` became `jruby-metrics` and `puppet-profiler`. We should consider dropping the `pe-` prefix from the metric names used by the example dashboards so that they are usable out of the box for monitoring open source installations in addition to PE installs.

Also, the `pe-` prefixes are currently still around for backwards compatibility, but we should assume they will disappear one day.

**Comment by suckatrash** [comment]
@Sharpie Thanks for the heads up on this!

**Comment by Sharpie** [comment]
Tuns out this would have required choosing between dropping support for PE versions older than 2017.3, or changing the `.json` files into EPP templates. An elegant way to solve this would be to use Grafana's support for adding a "Constant" variable, which is set once on import --- however the ability to set these does not appear to be exposed via the API.

In the end, we just forked the "Puppetserver Performance" dashboard that was sensitive to this and load the forked copy if PE is not detected. This issue should stay open though as we will need a better solution for this if the `pe-` prefix is dropped.

**Comment by suckatrash** [comment]
This is addressed by #85
