### ISSUE TITLE
SSL functionality depends on puppetlabs/puppet_agent

### ISSUE THREAD

**Issue by fvoges** [puppetlabs/puppet_metrics_dashboard#6]
Enabling SSL depends on facts provided by puppetlabs/puppet_agent (puppet_sslpaths).

The metadata.json file doesn't include that module as a dependency, and the README doesn't mention it either.

Since it's not a hard requirement, the README should mention it as a requirement for SSL.

**Comment by suckatrash** [comment]
This should be fixed now as of #30
