### ISSUE TITLE
remove periods from master_list in documentation

### ISSUE THREAD

**Issue by tkishel** [puppetlabs/puppet_metrics_dashboard#60]
The documentation includes `.` in `master_list` in the examples, but Graphite separates the hierarchy of the metrics with `.`, so specifying a FQDN instead of a HOSTNAME results in `no data points` in the dashboards.

**Comment by tkishel** [comment]
Prolly should update the documentation here to make HOSTNAME more obvious:

https://puppet.com/docs/pe/2019.1/getting_started_with_graphite.html

Also, we could use something like this to automate PuppetServer metrics configuration on the Masters:

```
# cat pe_node_group_pe_master_metrics_enabled.pp

$masters               = ['pe-201910-master.puppetdebug.vlan']
$metrics_graphite_host = 'pe-201910-agent.puppetdebug.vlan'
$metrics_server_id     = $facts['hostname']

pe_node_group { 'PE Master Metrics Enabled':
  ensure               => 'present',
  classes              => {
  'puppet_enterprise::profile::master' => {
    'metrics_graphite_enabled' => true,
    'metrics_graphite_host'    => $metrics_graphite_host,
    'metrics_server_id'        => $metrics_server_id,
  }
},
  environment          => 'production',
  parent               => 'PE Master',
  pinned               => $masters,
}

# puppet apply pe_node_group_pe_master_metrics_enabled.pp
```

**Comment by npwalker** [comment]
I you make a child group of PE Masters you can just use a `rule => '.*'` instead of `pinned` to match all nodes on the PE masters group.

**Comment by tkishel** [comment]
Resolved: https://github.com/puppetlabs/puppet_metrics_dashboard#configure-graphite
