### ISSUE TITLE
v2 fails to load puppetserver toml-rb gem

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppet_metrics_dashboard#67]
It looks like a new installation will fail with the error denoted in https://github.com/voxpupuli/puppet-telegraf/issues/124 and documented in <https://github.com/voxpupuli/puppet-telegraf/blob/master/README.md#setup>.

~~~
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- toml-rb
~~~

The workaround for PE is to install https://forge.puppet.com/puppetlabs/puppetserver_gem and add the following to the manifest.

~~~
  package {'toml-rb':
    ensure => present,
    provider => 'puppetserver_gem',
    notify => Service['pe-puppetserver']
  } 
~~~

**Comment by suckatrash** [comment]
#68 should cover this
