### ISSUE TITLE
Convert to using Litmus

### ISSUE THREAD

**Issue by genebean** [puppetlabs/puppet_metrics_dashboard#84]
We should convert this to [Litmus](https://github.com/puppetlabs/puppet_litmus)

**Comment by genebean** [comment]
@carabasdaniel / @glennsarti - think you all could take some of the learnings you have had from converting modules to using Litmus and help us get this one converted? There is some work in #71 from @jarretlavallee already that may help with this.

**Comment by glennsarti** [comment]
Looks like it's almost here.  One thing to note is shouldn't really be using `docker_exp`  in provision.yaml.  That's docker experimental.
