### ISSUE TITLE
Can't install above 1.0.3

### ISSUE THREAD

**Issue by voiprodrigo** [puppetlabs/puppet_metrics_dashboard#86]
Hi,

I can't install above 1.0.3 because I'm using inifile with version 3.1.0.

I see that in master the dependencies were updated and this would be resolved.

Is there an ETA for a new release with updated dependencies?

Thanks!

**Comment by voiprodrigo** [comment]
Had do downgrade inifile to be able to install last release.

**Comment by suckatrash** [comment]
@voiprodrigo We shipped a release on March 25th with the dependency fix.
